# Generated by Django 5.2.1 on 2026-03-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randini', '0002_remove_customer_phone_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
