# Generated by Django 5.2.1 on 2026-03-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randini', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
