# Generated by Django 5.2.1 on 2026-03-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randini', '0004_sparepart_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('van', 'Van'), ('other', 'Other')], max_length=20),
        ),
    ]
