# Generated by Django 5.2.1 on 2026-03-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randini', '0008_alter_customer_options_alter_booking_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
