# Generated by Django 5.2.1 on 2026-04-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randini', '0009_order_mpesa_amount_order_mpesa_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('engine', 'Engine Repair'), ('body', 'Body Work'), ('painting', 'Car Painting'), ('oil', 'Oil Change'), ('diagnostic', 'Vehicle Diagnostic'), ('other', 'Other')], max_length=20)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('van', 'Van'), ('other', 'Other')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this service', max_digits=10)),
                ('description', models.TextField(blank=True, help_text="Description of what's included in this service")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service_type', 'vehicle_type'],
                'unique_together': {('service_type', 'vehicle_type')},
            },
        ),
    ]
