# Generated by Django 5.2.1 on 2026-04-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randini', '0010_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='inquiry_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('service', 'Service Request'), ('parts', 'Spare Parts'), ('booking', 'Booking Inquiry'), ('complaint', 'Complaint'), ('feedback', 'Feedback'), ('other', 'Other')], default='general', max_length=50),
        ),
    ]
